---
output:
  github_document:
    html_preview: false
---

# postr

Prepare reproducible conference posters using R Markdown


## Overview

Although several workflows are currently available for academic
poster preparation none of them are ideal.
Commonly, point-and-click software is used to arrange poster content
regardless of the analysis pipeline.
Most of these software tools are proprietary, thus trapping our content.
Typical free and script based tools such as $\LaTeX$ might not be appealing
or seem as complex as using a point-and-click tool.

This package provides templates and helper functions to
prepare R Markdown based conference posters with a free and reproducible
workflow and
produce output both in html for hosting and png for printing.
Relies on the flexdashboard package to easily define poster layout.


## Dependencies

This poster template depends on the following R packages

- rmarkdown
- flexdashboard
- webshot


## Preparing a new poster

In order to use this poster template, you need to:

1. Install the [`odeleongt/postr`](https://github.com/odeleongt/postr) package
  from github `devtools::install_github("odeleongt/postr")`
2. Install the PhantomJS library `webshot::install_phantomjs()`
3. Create a new R Markdown document in Rstudio based on the poster template,
  or run `rmarkdown::draft("my_poster.Rmd", template = "poster", package = "postr")`
4. Render the poster as an html file: `rmarkdown::render("my_poster.Rmd")`
5. Convert the html file as a printable A1 image: `postr::render("my_poster.html")`


## References

- JJ Allaire, Yihui Xie, Jonathan McPherson, Javier Luraschi, Kevin Ushey, Aron Atkins, Hadley Wickham, Joe Cheng and
  Winston Chang (2017). rmarkdown: Dynamic Documents for R. R package version 1.8.
  https://CRAN.R-project.org/package=rmarkdown
- Barbara Borges and JJ Allaire (2017). flexdashboard: R Markdown Format for Flexible Dashboards. R package version 0.5.1.
  https://CRAN.R-project.org/package=flexdashboard
- Winston Chang (2017). webshot: Take Screenshots of Web Pages. R package version 0.5.0.
  https://CRAN.R-project.org/package=webshot
